### ISSUE TITLE
missing versioning throws error in rails-assets

### ISSUE THREAD

**Issue by Genkilabs** [davidcunningham/roboto-condensed#1]
I'd love to use this through rails-assets, but when trying to register the package listed on Bower (https://libraries.io/bower/roboto-condensed) into the rails-assets library (https://rails-assets.org/components/new) it throws

`roboto-condensed has no versions defined. Please create an issue in component's repository.`

Weirdly, I see 0.2 in both .json files. Thoughts?

**Comment by Genkilabs** [comment]
I think it might need to be semantically versioned. ie. 0.2.0 or something...

**Comment by davidcunningham** [comment]
Incorporated a pull request and updated version to 0.3.0
